version: "3"

services:
    project129db:
        environment:
            - POSTGRES_DB=ProjectName
            - POSTGRES_USER=agent4ProjectName
            - POSTGRES_PASSWORD=v3ry23C93tp422w0Rd
        image: project129/project129db
        hostname: project129db
        container_name: project129db
        labels:
            - SERVICE_NAME=project129db
        volumes:
            - postgres:/var/lib/postgresql/data
        expose:
            - 5432
        ports:
            - 5432:5432

    project129web:
        links:
            - project129db
        depends_on:
            - project129db
        image: project129/project129web
        hostname: project129web
        expose:
            - 5000
        ports:
            - 5000:5000
        container_name: project129web
        environment:
            - DB_HOST=project129db
            - DB_USER_NAME=agent4ProjectName
            - DB_USER_PASSWORD=v3ry23C93tp422w0Rd
            - DB_NAME=ProjectName
            - APP_ENV=prod
            - VIRTUAL_HOST=project129web
        labels:
            - SERVICE_NAME=project129web
        command: /bin/sh -c "envsubst < appsettings.json > temp.json && mv -f temp.json appsettings.json && dotnet ProjectName.RestApiServer.dll"
# sed -i "s|%$ENV_KEY1%|$ENV_VALUE1|g;s|%$ENV_KEY2%|$ENV_VALUE2|g" appsettings.json

volumes:
    postgres: