version: "3"

services:
    project129db:
        environment:
            - POSTGRES_DB=ProjectName
            - POSTGRES_USER=agent4ProjectName
            - POSTGRES_PASSWORD=v3ry23C93tp422w0Rd
        image: project129/project129db
        hostname: project129db
        container_name: project129db
        labels:
            - SERVICE_NAME=project129db
        volumes:
            - postgres:/var/lib/postgresql/data
        expose:
            - 5432
        ports:
            - 5432:5432

volumes:
    postgres: